//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace graunt.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageDefault {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageDefault() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("graunt.Resources.LanguageDefault", typeof(LanguageDefault).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string about_author {
            get {
                return ResourceManager.GetString("about.author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string about_close {
            get {
                return ResourceManager.GetString("about.close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License.
        /// </summary>
        internal static string about_license {
            get {
                return ResourceManager.GetString("about.license", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string about_title {
            get {
                return ResourceManager.GetString("about.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        internal static string about_version {
            get {
                return ResourceManager.GetString("about.version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        internal static string analyse_mean {
            get {
                return ResourceManager.GetString("analyse.mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        internal static string analyse_median {
            get {
                return ResourceManager.GetString("analyse.median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation.
        /// </summary>
        internal static string analyse_standardDeviation {
            get {
                return ResourceManager.GetString("analyse.standardDeviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance.
        /// </summary>
        internal static string analyse_variance {
            get {
                return ResourceManager.GetString("analyse.variance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select columns which should be imported..
        /// </summary>
        internal static string columnSelect_header {
            get {
                return ResourceManager.GetString("columnSelect.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not import.
        /// </summary>
        internal static string columnSelect_ignore {
            get {
                return ResourceManager.GetString("columnSelect.ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string columnSelect_import {
            get {
                return ResourceManager.GetString("columnSelect.import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string columnSelect_next {
            get {
                return ResourceManager.GetString("columnSelect.next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string columnSelect_title {
            get {
                return ResourceManager.GetString("columnSelect.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad value treatment.
        /// </summary>
        internal static string dataType_badValue {
            get {
                return ResourceManager.GetString("dataType.badValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string dataType_column {
            get {
                return ResourceManager.GetString("dataType.column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use.
        /// </summary>
        internal static string dataType_custom {
            get {
                return ResourceManager.GetString("dataType.custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use empty value.
        /// </summary>
        internal static string dataType_empty {
            get {
                return ResourceManager.GetString("dataType.empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use mean.
        /// </summary>
        internal static string dataType_mean {
            get {
                return ResourceManager.GetString("dataType.mean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use median.
        /// </summary>
        internal static string dataType_median {
            get {
                return ResourceManager.GetString("dataType.median", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string dataType_next {
            get {
                return ResourceManager.GetString("dataType.next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        internal static string dataType_numeric {
            get {
                return ResourceManager.GetString("dataType.numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real.
        /// </summary>
        internal static string dataType_real {
            get {
                return ResourceManager.GetString("dataType.real", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip whole record.
        /// </summary>
        internal static string dataType_skip {
            get {
                return ResourceManager.GetString("dataType.skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string dataType_text {
            get {
                return ResourceManager.GetString("dataType.text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string dataType_title {
            get {
                return ResourceManager.GetString("dataType.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string dataType_type {
            get {
                return ResourceManager.GetString("dataType.type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data to analyse! Start with opening the data file..
        /// </summary>
        internal static string error_analyseNothingMessage {
            get {
                return ResourceManager.GetString("error.analyseNothingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing data.
        /// </summary>
        internal static string error_analyseNothingTitle {
            get {
                return ResourceManager.GetString("error.analyseNothingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data you filled are in wrong format. Do you want to clear the cell?.
        /// </summary>
        internal static string error_badFormatMessage {
            get {
                return ResourceManager.GetString("error.badFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bad value.
        /// </summary>
        internal static string error_badFormatTitle {
            get {
                return ResourceManager.GetString("error.badFormatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not open file.
        /// </summary>
        internal static string error_openErrorMessage {
            get {
                return ResourceManager.GetString("error.openErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening file error.
        /// </summary>
        internal static string error_openErrorTitle {
            get {
                return ResourceManager.GetString("error.openErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes made in file.
        /// </summary>
        internal static string error_saveConfirmMessage {
            get {
                return ResourceManager.GetString("error.saveConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string error_saveConfirmTitle {
            get {
                return ResourceManager.GetString("error.saveConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not write to file.
        /// </summary>
        internal static string error_saveErrorMessage {
            get {
                return ResourceManager.GetString("error.saveErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving file error.
        /// </summary>
        internal static string error_saveErrorTitle {
            get {
                return ResourceManager.GetString("error.saveErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to save..
        /// </summary>
        internal static string error_saveNothinMessage {
            get {
                return ResourceManager.GetString("error.saveNothinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice.
        /// </summary>
        internal static string error_saveNothinTitle {
            get {
                return ResourceManager.GetString("error.saveNothinTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings saved. The chnanges will be visible after restart..
        /// </summary>
        internal static string error_settingsSavedMessage {
            get {
                return ResourceManager.GetString("error.settingsSavedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        internal static string error_settingsSavedTitle {
            get {
                return ResourceManager.GetString("error.settingsSavedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma (,).
        /// </summary>
        internal static string import_comma {
            get {
                return ResourceManager.GetString("import.comma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma separated values.
        /// </summary>
        internal static string import_commaSeparatedValues {
            get {
                return ResourceManager.GetString("import.commaSeparatedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom format.
        /// </summary>
        internal static string import_customFormat {
            get {
                return ResourceManager.GetString("import.customFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double quote (&quot;).
        /// </summary>
        internal static string import_doubleQuote {
            get {
                return ResourceManager.GetString("import.doubleQuote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File encoding.
        /// </summary>
        internal static string import_encoding {
            get {
                return ResourceManager.GetString("import.encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field separator.
        /// </summary>
        internal static string import_fieldSeparator {
            get {
                return ResourceManager.GetString("import.fieldSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format.
        /// </summary>
        internal static string import_fileFormat {
            get {
                return ResourceManager.GetString("import.fileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First row contains names of columns.
        /// </summary>
        internal static string import_hasHeader {
            get {
                return ResourceManager.GetString("import.hasHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too many columns to display.
        /// </summary>
        internal static string import_manyColumnsError {
            get {
                return ResourceManager.GetString("import.manyColumnsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line.
        /// </summary>
        internal static string import_newline {
            get {
                return ResourceManager.GetString("import.newline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string import_next {
            get {
                return ResourceManager.GetString("import.next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string import_none {
            get {
                return ResourceManager.GetString("import.none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string import_openDialogTitle {
            get {
                return ResourceManager.GetString("import.openDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to parse data.
        /// </summary>
        internal static string import_parseError {
            get {
                return ResourceManager.GetString("import.parseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice: This is preview of the first 10 records. The rest does not have to be readable..
        /// </summary>
        internal static string import_partial {
            get {
                return ResourceManager.GetString("import.partial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string import_reason {
            get {
                return ResourceManager.GetString("import.reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record separator.
        /// </summary>
        internal static string import_recordSeparator {
            get {
                return ResourceManager.GetString("import.recordSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon (;).
        /// </summary>
        internal static string import_semicolon {
            get {
                return ResourceManager.GetString("import.semicolon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semicolon separated values.
        /// </summary>
        internal static string import_semicolonSeparatedValues {
            get {
                return ResourceManager.GetString("import.semicolonSeparatedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For special character use this squence: newline &quot;\n&quot;, tab &quot;\t&quot;.
        /// </summary>
        internal static string import_specialCharactersHint {
            get {
                return ResourceManager.GetString("import.specialCharactersHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        internal static string import_tab {
            get {
                return ResourceManager.GetString("import.tab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab separated values.
        /// </summary>
        internal static string import_tabSeparatedValues {
            get {
                return ResourceManager.GetString("import.tabSeparatedValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text delimiter.
        /// </summary>
        internal static string import_textDelimiter {
            get {
                return ResourceManager.GetString("import.textDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string import_title {
            get {
                return ResourceManager.GetString("import.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string initial_buttonImport {
            get {
                return ResourceManager.GetString("initial.buttonImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string initial_buttonOpen {
            get {
                return ResourceManager.GetString("initial.buttonOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently open.
        /// </summary>
        internal static string initial_labelRecent {
            get {
                return ResourceManager.GetString("initial.labelRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string initial_labelStart {
            get {
                return ResourceManager.GetString("initial.labelStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string main_openDialog {
            get {
                return ResourceManager.GetString("main.openDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string main_saveDialog {
            get {
                return ResourceManager.GetString("main.saveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string mean_calculate {
            get {
                return ResourceManager.GetString("mean.calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - result is either too small or too big to display.
        /// </summary>
        internal static string mean_dataTypeExceded {
            get {
                return ResourceManager.GetString("mean.dataTypeExceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select columns from which should be mean calculated..
        /// </summary>
        internal static string mean_header {
            get {
                return ResourceManager.GetString("mean.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        internal static string mean_method {
            get {
                return ResourceManager.GetString("mean.method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible columns.
        /// </summary>
        internal static string mean_possible {
            get {
                return ResourceManager.GetString("mean.possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate from.
        /// </summary>
        internal static string mean_selected {
            get {
                return ResourceManager.GetString("mean.selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean.
        /// </summary>
        internal static string mean_title {
            get {
                return ResourceManager.GetString("mean.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string median_calculate {
            get {
                return ResourceManager.GetString("median.calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - result is either too small or too big to display.
        /// </summary>
        internal static string median_dataTypeExceded {
            get {
                return ResourceManager.GetString("median.dataTypeExceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select columns from which should be median calculated..
        /// </summary>
        internal static string median_header {
            get {
                return ResourceManager.GetString("median.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        internal static string median_method {
            get {
                return ResourceManager.GetString("median.method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible columns.
        /// </summary>
        internal static string median_possible {
            get {
                return ResourceManager.GetString("median.possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate from.
        /// </summary>
        internal static string median_selected {
            get {
                return ResourceManager.GetString("median.selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median.
        /// </summary>
        internal static string median_title {
            get {
                return ResourceManager.GetString("median.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string menu_about {
            get {
                return ResourceManager.GetString("menu.about", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse.
        /// </summary>
        internal static string menu_analyse {
            get {
                return ResourceManager.GetString("menu.analyse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string menu_file {
            get {
                return ResourceManager.GetString("menu.file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string menu_help {
            get {
                return ResourceManager.GetString("menu.help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import....
        /// </summary>
        internal static string menu_import {
            get {
                return ResourceManager.GetString("menu.import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string menu_open {
            get {
                return ResourceManager.GetString("menu.open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File....
        /// </summary>
        internal static string menu_openFile {
            get {
                return ResourceManager.GetString("menu.openFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results.
        /// </summary>
        internal static string menu_results {
            get {
                return ResourceManager.GetString("menu.results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string menu_save {
            get {
                return ResourceManager.GetString("menu.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as....
        /// </summary>
        internal static string menu_saveAs {
            get {
                return ResourceManager.GetString("menu.saveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string menu_settings {
            get {
                return ResourceManager.GetString("menu.settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User guide [online].
        /// </summary>
        internal static string menu_userGuide {
            get {
                return ResourceManager.GetString("menu.userGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string parser_column {
            get {
                return ResourceManager.GetString("parser.column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns has to have different names.
        /// </summary>
        internal static string parser_columnNameError {
            get {
                return ResourceManager.GetString("parser.columnNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file format is not same as the format of data.
        /// </summary>
        internal static string parser_dataFormatError {
            get {
                return ResourceManager.GetString("parser.dataFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record separator and Field separator can not be empty.
        /// </summary>
        internal static string parser_emptyCharactersError {
            get {
                return ResourceManager.GetString("parser.emptyCharactersError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header name can not be empty.
        /// </summary>
        internal static string parser_emptyHeaderError {
            get {
                return ResourceManager.GetString("parser.emptyHeaderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record separator, Field separator and Text delimiter has to be different characters.
        /// </summary>
        internal static string parser_sameCharacterError {
            get {
                return ResourceManager.GetString("parser.sameCharacterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to append empty cells.
        /// </summary>
        internal static string rectangular_append {
            get {
                return ResourceManager.GetString("rectangular.append", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to crop.
        /// </summary>
        internal static string rectangular_crop {
            get {
                return ResourceManager.GetString("rectangular.crop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records are not in rectangular shape..
        /// </summary>
        internal static string rectangular_header {
            get {
                return ResourceManager.GetString("rectangular.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to do not import.
        /// </summary>
        internal static string rectangular_ignore {
            get {
                return ResourceManager.GetString("rectangular.ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longer records.
        /// </summary>
        internal static string rectangular_longer {
            get {
                return ResourceManager.GetString("rectangular.longer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string rectangular_next {
            get {
                return ResourceManager.GetString("rectangular.next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shorter records.
        /// </summary>
        internal static string rectangular_shorter {
            get {
                return ResourceManager.GetString("rectangular.shorter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string rectangular_title {
            get {
                return ResourceManager.GetString("rectangular.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last valid column.
        /// </summary>
        internal static string rectangular_validColumn {
            get {
                return ResourceManager.GetString("rectangular.validColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string result_clear {
            get {
                return ResourceManager.GetString("result.clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string result_hide {
            get {
                return ResourceManager.GetString("result.hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save....
        /// </summary>
        internal static string result_save {
            get {
                return ResourceManager.GetString("result.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as.
        /// </summary>
        internal static string result_saveDialog {
            get {
                return ResourceManager.GetString("result.saveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        internal static string result_title {
            get {
                return ResourceManager.GetString("result.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string settings_cancel {
            get {
                return ResourceManager.GetString("settings.cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string settings_language {
            get {
                return ResourceManager.GetString("settings.language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string settings_save {
            get {
                return ResourceManager.GetString("settings.save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_settings {
            get {
                return ResourceManager.GetString("settings.settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string settings_title {
            get {
                return ResourceManager.GetString("settings.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string standardDeviation_calculate {
            get {
                return ResourceManager.GetString("standardDeviation.calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - result is either too small or too big to display.
        /// </summary>
        internal static string standardDeviation_dataTypeExceded {
            get {
                return ResourceManager.GetString("standardDeviation.dataTypeExceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select columns from which should be standard deviation calculated..
        /// </summary>
        internal static string standardDeviation_header {
            get {
                return ResourceManager.GetString("standardDeviation.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation.
        /// </summary>
        internal static string standardDeviation_method {
            get {
                return ResourceManager.GetString("standardDeviation.method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible columns.
        /// </summary>
        internal static string standardDeviation_possible {
            get {
                return ResourceManager.GetString("standardDeviation.possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate from.
        /// </summary>
        internal static string standardDeviation_selected {
            get {
                return ResourceManager.GetString("standardDeviation.selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard deviation.
        /// </summary>
        internal static string standardDeviation_title {
            get {
                return ResourceManager.GetString("standardDeviation.title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string variance_calculate {
            get {
                return ResourceManager.GetString("variance.calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error - result is either too small or too big to display.
        /// </summary>
        internal static string variance_dataTypeExceded {
            get {
                return ResourceManager.GetString("variance.dataTypeExceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select columns from which should be variance calculated..
        /// </summary>
        internal static string variance_header {
            get {
                return ResourceManager.GetString("variance.header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance.
        /// </summary>
        internal static string variance_method {
            get {
                return ResourceManager.GetString("variance.method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible columns.
        /// </summary>
        internal static string variance_possible {
            get {
                return ResourceManager.GetString("variance.possible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate from.
        /// </summary>
        internal static string variance_selected {
            get {
                return ResourceManager.GetString("variance.selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variance.
        /// </summary>
        internal static string variance_title {
            get {
                return ResourceManager.GetString("variance.title", resourceCulture);
            }
        }
    }
}
